name: addcolumns
description: Add metadata information to an existing file as additional columns
keywords:
  - columns
  - metadata
  - awk
tools:
  - gawk:
      description: "GNU awk"
      homepage: "https://www.gnu.org/software/gawk/"
      documentation: "https://www.gnu.org/software/gawk/manual/"
      tool_dev_url: "https://www.gnu.org/prep/ftp.html"
      licence:
        - "GPL v3"
      identifier: ""
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        The following keys are added in additional columns to the input file.
        e.g. [ id:'test', depth:1, gparray:'illumina', tools:'glimpse', panel:'1000G' ]
  - input:
      type: file
      description: Textual format file
output:
  txt:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - txt:
        type: file
        description: Resulting file with additional columns containing the metadata information
        pattern: "*.txt"
  versions_gawk:
    - - ${task.process}:
          type: string
          description: The name of the process
      - gawk:
          type: string
          description: The name of the tool
      - awk -Wversion | sed '1!d; s/.*Awk //; s/,.*//':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - gawk:
          type: string
          description: The name of the tool
      - awk -Wversion | sed '1!d; s/.*Awk //; s/,.*//':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@louislenezet"
maintainers:
  - "@louislenezet"
