bump_version: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: Louis Le Nezet, Anabella Trigila
  description: Phasing and imputation pipeline
  force: false
  is_nfcore: true
  name: phaseimpute
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0.0
update: null
