# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "MAP_DETECT_CONVERT_GAWK"
description: Subworkflow to automatically detect genetic map format and convert it to all known formats
keywords:
  - map
  - convertion
  - format
components:
  - mapconvert
  - mapautodetect
input:
  - ch_map:
      description: Channel with input genetic map
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. [ id:'test' ]
        - map_file:
            type: file
            description: Genomic map file to process
        - sep:
            type: string
            description: Separator used in the input map file
        - header:
            type: boolean
            description: Whether the input map file contains a header line
        - colnames:
            type: string
            description: |
              Comma-separated list of column names in the input map file
              Recognized names are: chr, pos, cM, rate and id
output:
  - map_glimpse:
      description: Channel with glimpse map format
      structure:
        - meta:
            type: map
            description: |
              Groovy Map containing sample information
              e.g. [ id:'test', single_end:false ]
        - "*.glimpse.map":
            type: file
            description: |
              File containing the map in Glimpse format:
              tab-delimited file with header and columns:
              pos, chr, cM
            pattern: "*.glimpse.map"
  - map_plink:
      description: Channel with plink map format
      structure:
        - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
        - "*.plink.map":
          type: file
          description: |
            File containing the map in PLINK format:
            space-delimited file without header and columns:
            chr, id, cM, pos
          pattern: "*.plink.map"
  - map_stitch:
      description: Channel with stitch map format
      structure:
        - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
        - "*.stitch.map":
          type: file
          description: |
            File containing the map in STITCH format:
            space-delimited file with header and columns:
            pos, rate, cM
          pattern: "*.stitch.map"
  - map_minimac:
      description: Channel with minimac map format
      structure:
        - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
        - "*.minimac.map":
          type: file
          description: |
            File containing the map in Minimac format:
            tab-delimited file with header and columns:
            chr, pos, cM
          pattern: "*.minimac.map"
authors:
  - "@louislenezet"
maintainers:
  - "@louislenezet"
